### ISSUE TITLE
Need a bit clarification

### ISSUE THREAD

**Issue by krishnaanaril** [morris821028/UVa#19]
Hi morris821028,

In the solution '10065 - Useless Tile Packers', why you are using the following code to find the hull area.
`double cont = calc_area(CH, m-1);`
Especially the '**m-1**' part. Is the algorithm returns actual hull?

Thanks

**Comment by morris821028** [comment]
`int monotone(int n) { ... return m; }`  is old version which I write. This convex hull has point ch(0), ch(1), ch(2), ..., ch(m-2), ch(m-1). Actually, ch(0) equals ch(m-1) by monotone chain implementation, so it has m-1 points.

**Comment by krishnaanaril** [comment]
Okay, That was helpful. Thanks a lot.
