### ISSUE TITLE
Unable to run all test cases

### ISSUE THREAD

**Issue by chandankr** [morris821028/UVa#20]
Hi, 
i just simply run this program but could not run all test cases. Problem #868
Numerical Maze

**Comment by alsmadi** [comment]
I am not sure what is this email about ?

On Thu, Jun 16, 2016 at 10:15 AM, chandankr <notifications@github.com>
wrote:

> Hi,
> i just simply run this program but could not run all test cases. Problem
> #868
> Numerical Maze
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/morris821028/UVa/issues/20>, or mute the thread
> <https://github.com/notifications/unsubscribe/AGTGKHZWoMMuo3wNMrlRCeGPdokOAmV2ks5qMVqGgaJpZM4I3blf>
> .
>



-- 
Izzat Alsmadi
Phd
software engineering

**Comment by alsmadi** [comment]
Izzat Alsmadi has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=1024674817942-fstip2shineo1lsego38uvsg8n2d3421.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.g-docs.pro%2Fg.php&customparam=customparam>
